import { ArrowForward } from "@mui/icons-material";
import { Grid, Stack, Typography, useMediaQuery } from "@mui/material";
import { Box } from "@mui/system";
import LeftImage from "../../assets/images/Rectangle5.png";
import RightImage from "../../assets/images/Rectangle6.png";
import Button from "../Button";
import { useTheme } from "@mui/material/styles";

const Section2 = () => {
  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down("sm"));
  return (
    <>
      <Grid container direction={"row"} spacing={4}>
        <Grid item md={6} align="right">
          <Box className="relative" data-aos="slide-right">
            <img
              src={LeftImage}
              className="object-cover"
              alt="logo"
              width="100%"
            />
            <Box
              sx={{
                position: "absolute",
                top: 0,
                left: 0,
                height: "100%",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
              }}
              className="backdrop-blur-[1px]"
            >
              <Stack spacing={3} sx={{ padding: "20%" }}>
                <Typography
                  variant="h4"
                  className="font-jost text-white pt-1"
                  sx={{ fontWeight: "700" }}
                  component="div"
                  align="left"
                >
                  I’m a Clean Energy Producer
                </Typography>
                {!isMobile ? (
                  <Typography
                    variant="body1"
                    className="font-open-sans text-white"
                    component="div"
                    align="left"
                  >
                    Do you have solar on your rooftop? Are you considering a
                    solar installation? Please sign-up for the platform as a
                    Clean Energy Producer. Producers own renewable energy
                    systems and will be paired with households in need of
                    electricity bill relief within your community. These
                    households will receive donations of utility bill credits
                    generated by your solar system.
                  </Typography>
                ) : null}
                <Button
                  name={
                    <>
                      Register now
                      <ArrowForward
                        sx={{
                          height: "15px",
                          marginBottom: "4px",
                        }}
                      />
                    </>
                  }
                  padding="10px 14px"
                  width="12rem"
                  textVariant="body1"
                ></Button>
              </Stack>
            </Box>
          </Box>
        </Grid>
        <Grid item md={6}>
          <div className="relative" data-aos="slide-left">
            <img
              src={RightImage}
              className="object-cover"
              alt="logo"
              width="100%"
            />
            <Box
              sx={{
                position: "absolute",
                top: 0,
                left: 0,
                width: "100%",
                height: "100%",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
              }}
              className="backdrop-blur-[1px]"
            >
              <Stack
                spacing={4}
                justifyContent="center"
                alignItems="center"
                sx={{ padding: "9rem" }}
              >
                <Typography
                  variant="h4"
                  className="font-primary text-white"
                  sx={{ fontWeight: "700" }}
                  component="div"
                >
                  I’m a Clean Energy Consumer
                </Typography>
              </Stack>
            </Box>
          </div>
        </Grid>
      </Grid>
    </>
  );
};
export default Section2;
